name: Go Build and Test
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Go Build
        run: |
          ls -ltr | grep drw | awk '{print $9}' | while read dir_name 
          do
          cd $dir_name
          echo "Running Build in $dir_name"
          go build -v ./...
          cd ..
          done
        working-directory: src
      - name: Go Tests
        run: |
          ls -ltr | grep drw | awk '{print $9}' | while read dir_name 
          do
          cd $dir_name
          echo "Running Test in $dir_name"
          go test -v ./...
          cd ..
          done
        working-directory: src
